<?xml version="1.0" encoding="utf-8"?>
<Database Name="OMM" Class="OMMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=BRAC-E9434D5251\SQLEXPRESS;Initial Catalog=OMM;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BUDI2_NS" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Message_Recipients" Member="Message_Recipients">
    <Type Name="Message_Recipient">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Message_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Recipient_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Recipient_Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Destination" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Try_Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SMS_Credits" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="Is_Phone_Number" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SMS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SMS_Status_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Updated_On" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Message_Statuse_Message_Recipient" Member="Message_Statuse" ThisKey="Status_ID" OtherKey="ID" Type="Message_Statuse" IsForeignKey="true" />
      <Association Name="Message_Message_Recipient" Member="Message" ThisKey="Message_ID" OtherKey="ID" Type="Message" IsForeignKey="true" />
      <Association Name="SMS_Message_Message_Recipient" Member="SMS_Message" ThisKey="SMS_ID" OtherKey="ID" Type="SMS_Message" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message_Statuses" Member="Message_Statuses">
    <Type Name="Message_Statuse">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Message_Statuse_Message_Recipient" Member="Message_Recipients" ThisKey="ID" OtherKey="Status_ID" Type="Message_Recipient" />
    </Type>
  </Table>
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Delivered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Message_Message_Recipient" Member="Message_Recipients" ThisKey="ID" OtherKey="Message_ID" Type="Message_Recipient" />
    </Type>
  </Table>
  <Table Name="dbo.ClientContacts" Member="ClientContacts">
    <Type Name="ClientContact">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="JobTitle" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CountryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChangedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Imported" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ClientContact_Enquiry" Member="Enquiries" ThisKey="ID" OtherKey="ContactID" Type="Enquiry" />
      <Association Name="ClientContact_Quotation" Member="Quotations" ThisKey="ID" OtherKey="SubmittedToClientContactID" Type="Quotation" />
      <Association Name="Client_ClientContact" Member="Client" ThisKey="CompanyID" OtherKey="ID" Type="Client" IsForeignKey="true" />
      <Association Name="Country_ClientContact" Member="Country" ThisKey="CountryID" OtherKey="ID" Type="Country" IsForeignKey="true" />
      <Association Name="User_ClientContact" Member="User" ThisKey="ChangedByUserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Postcode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Web" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ChangedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Client_ClientContact" Member="ClientContacts" ThisKey="ID" OtherKey="CompanyID" Type="ClientContact" />
      <Association Name="Country_Client" Member="Country" ThisKey="CountryID" OtherKey="ID" Type="Country" IsForeignKey="true" />
      <Association Name="User_Client" Member="User" ThisKey="ChangedByUserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Countries" Member="Countries">
    <Type Name="Country">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsUK" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsEurope" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="Country_ClientContact" Member="ClientContacts" ThisKey="ID" OtherKey="CountryID" Type="ClientContact" />
      <Association Name="Country_Client" Member="Clients" ThisKey="ID" OtherKey="CountryID" Type="Client" />
    </Type>
  </Table>
  <Table Name="dbo.Enquiries" Member="Enquiries">
    <Type Name="Enquiry">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ChangedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="CreatedByUsername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChangedByUsername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EnguirySubject" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Enquiry_EnquiryLine" Member="EnquiryLines" ThisKey="ID" OtherKey="EnquiryID" Type="EnquiryLine" />
      <Association Name="Enquiry_Quotation" Member="Quotations" ThisKey="ID" OtherKey="EnquiryID" Type="Quotation" />
      <Association Name="ClientContact_Enquiry" Member="ClientContact" ThisKey="ContactID" OtherKey="ID" Type="ClientContact" IsForeignKey="true" />
      <Association Name="EnquiryType_Enquiry" Member="EnquiryType" ThisKey="TypeID" OtherKey="ID" Type="EnquiryType" IsForeignKey="true" />
      <Association Name="User_Enquiry" Member="User" ThisKey="CreatedByUserID" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="User_Enquiry1" Member="User1" ThisKey="ChangedByUserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EnquiryTypes" Member="EnquiryTypes">
    <Type Name="EnquiryType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumberSuffix" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="EnquiryType_Enquiry" Member="Enquiries" ThisKey="ID" OtherKey="TypeID" Type="Enquiry" />
    </Type>
  </Table>
  <Table Name="dbo.EnquiryLines" Member="EnquiryLines">
    <Type Name="EnquiryLine">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnquiryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ChangedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Enquiry_EnquiryLine" Member="Enquiry" ThisKey="EnquiryID" OtherKey="ID" Type="Enquiry" IsForeignKey="true" />
      <Association Name="User_EnquiryLine" Member="User" ThisKey="ChangedByUserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserInRole" Member="UserInRoles">
    <Type Name="UserInRole">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Role_UserInRole" Member="Role" ThisKey="RoleID" OtherKey="ID" Type="Role" IsForeignKey="true" />
      <Association Name="User_UserInRole" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="User_UserInRole1" Member="User1" ThisKey="ModifiedBy" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ChangedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Role_UserInRole" Member="UserInRoles" ThisKey="ID" OtherKey="RoleID" Type="UserInRole" />
      <Association Name="User_Role" Member="User" ThisKey="ChangedByUserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Quotations" Member="Quotations">
    <Type Name="Quotation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EnquiryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subcontractor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ScopeOfWork" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MainEquipment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ValidityDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Schedule" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SubmissionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DecisionSuccessful" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DecisionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ChangedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="SubmittedToClientContactID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrencyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByUsername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChangedByUsername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Contract_awarded_to" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Contract_awarded_Value" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewStatusID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Quotation_QuotationPricingLine" Member="QuotationPricingLines" ThisKey="ID" OtherKey="QuotationID" Type="QuotationPricingLine" />
      <Association Name="Quotation_Project" Member="Projects" ThisKey="ID" OtherKey="QuotationID" Type="Project" />
      <Association Name="ClientContact_Quotation" Member="ClientContact" ThisKey="SubmittedToClientContactID" OtherKey="ID" Type="ClientContact" IsForeignKey="true" />
      <Association Name="Enquiry_Quotation" Member="Enquiry" ThisKey="EnquiryID" OtherKey="ID" Type="Enquiry" IsForeignKey="true" />
      <Association Name="QuotationStatuse_Quotation" Member="QuotationStatuse" ThisKey="StatusID" OtherKey="ID" Type="QuotationStatuse" IsForeignKey="true" />
      <Association Name="Currency_Quotation" Member="Currency" ThisKey="CurrencyID" OtherKey="ID" Type="Currency" IsForeignKey="true" />
      <Association Name="User_Quotation" Member="User" ThisKey="ChangedByUserID" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="User_Quotation1" Member="User1" ThisKey="CreatedByUserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuotationPricingTypes" Member="QuotationPricingTypes">
    <Type Name="QuotationPricingType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="QuotationPricingType_QuotationPricingLine" Member="QuotationPricingLines" ThisKey="ID" OtherKey="PricingTypeID" Type="QuotationPricingLine" />
    </Type>
  </Table>
  <Table Name="dbo.QuotationPricingLines" Member="QuotationPricingLines">
    <Type Name="QuotationPricingLine">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuotationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PricingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="QuotationPricingType_QuotationPricingLine" Member="QuotationPricingType" ThisKey="PricingTypeID" OtherKey="ID" Type="QuotationPricingType" IsForeignKey="true" />
      <Association Name="Quotation_QuotationPricingLine" Member="Quotation" ThisKey="QuotationID" OtherKey="ID" Type="Quotation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuotationStatuses" Member="QuotationStatuses">
    <Type Name="QuotationStatuse">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="QuotationStatuse_Quotation" Member="Quotations" ThisKey="ID" OtherKey="StatusID" Type="Quotation" />
    </Type>
  </Table>
  <Table Name="dbo.Currency" Member="Currencies">
    <Type Name="Currency">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShortCode" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Currency_Quotation" Member="Quotations" ThisKey="ID" OtherKey="CurrencyID" Type="Quotation" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Project">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QuotationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ChangedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="CreatedByUsername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChangedByUsername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Quotation_Project" Member="Quotation" ThisKey="QuotationID" OtherKey="ID" Type="Quotation" IsForeignKey="true" />
      <Association Name="User_Project" Member="User" ThisKey="CreatedByUserID" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="User_Project1" Member="User1" ThisKey="ChangedByUserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserNameWeb" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="User_ClientContact" Member="ClientContacts" ThisKey="ID" OtherKey="ChangedByUserID" Type="ClientContact" />
      <Association Name="User_Client" Member="Clients" ThisKey="ID" OtherKey="ChangedByUserID" Type="Client" />
      <Association Name="User_Enquiry" Member="Enquiries" ThisKey="ID" OtherKey="CreatedByUserID" Type="Enquiry" />
      <Association Name="User_Enquiry1" Member="Enquiries1" ThisKey="ID" OtherKey="ChangedByUserID" Type="Enquiry" />
      <Association Name="User_EnquiryLine" Member="EnquiryLines" ThisKey="ID" OtherKey="ChangedByUserID" Type="EnquiryLine" />
      <Association Name="User_UserInRole" Member="UserInRoles" ThisKey="ID" OtherKey="UserID" Type="UserInRole" />
      <Association Name="User_UserInRole1" Member="UserInRoles1" ThisKey="ID" OtherKey="ModifiedBy" Type="UserInRole" />
      <Association Name="User_Role" Member="Roles" ThisKey="ID" OtherKey="ChangedByUserID" Type="Role" />
      <Association Name="User_Quotation" Member="Quotations" ThisKey="ID" OtherKey="ChangedByUserID" Type="Quotation" />
      <Association Name="User_Quotation1" Member="Quotations1" ThisKey="ID" OtherKey="CreatedByUserID" Type="Quotation" />
      <Association Name="User_Project" Member="Projects" ThisKey="ID" OtherKey="CreatedByUserID" Type="Project" />
      <Association Name="User_Project1" Member="Projects1" ThisKey="ID" OtherKey="ChangedByUserID" Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.SMS_Messages" Member="SMS_Messages">
    <Type Name="SMS_Message">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Client_Ref" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sent_On" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SMS_Message_Message_Recipient" Member="Message_Recipients" ThisKey="ID" OtherKey="SMS_ID" Type="Message_Recipient" />
    </Type>
  </Table>
  <Function Name="dbo.GenerateNewQuotationNumber" Method="GenerateNewQuotationNumber" IsComposable="true">
    <Parameter Name="EnquiryID" Parameter="enquiryID" Type="System.Int32" DbType="Int" />
    <Parameter Name="WithVersion" Parameter="withVersion" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.GenerateNewProjectNumber" Method="GenerateNewProjectNumber" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.GenerateNewEnquiryNumber" Method="GenerateNewEnquiryNumber" IsComposable="true">
    <Parameter Name="EnquiryTypeID" Parameter="enquiryTypeID" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.reportMonthlyEnquery" Method="reportMonthlyEnquery">
    <ElementType Name="reportMonthlyEnqueryResult">
      <Column Name="MonthName" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalInitiated" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Outstanding" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quoted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Closed" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.reportMonthlyQuotations" Method="reportMonthlyQuotations">
    <ElementType Name="reportMonthlyQuotationsResult">
      <Column Name="MonthName" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalInitiated" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NotSubmitted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Submitted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Unsuccessful" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Successful" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequoteRequested" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Revised" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Closed" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>